### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by jodaka** [chrisjdavies/vscode-grep-panel#1]
I'm on mac and have ripgrep installed and available under 'rg' command. When I installed extension (ver 0.2) and tried to run grep, first I get a dialog and enter grep query. Then either nothing happens or I get "Failed to run any grep command" notification from vscode.

**Comment by jodaka** [comment]
Actually it does work, but I'm just being dumb. I had to go View > Appearance > Panel and turn it on. Would be nice if grep could automatically make it visible. 

I'm going to leave this issue just in case someone as dumb as me couldn't figure out how to use this extensions and end up here.

**Comment by chrisjdavies** [comment]
Hey. Thanks for reporting. I looked into this since I've seen the error pop up before; turns out I wasn't properly distinguishing between zero grep results vs. no greps succeeding. Fixed that now in 0.0.3.

Also added your recommendation to have the grep panel show after the search completes.

Published to the VSCode Extension Marketplace. Just waiting for it to run through their automated tests and you should be able to update in a few minutes.

**Comment by chrisjdavies** [comment]
Published and confirmed it's now available. Let me know if you have any other issues. This already feels much better to have the results come into view after a search completes!

**Comment by jodaka** [comment]
Thank was fast, thanks! I believe that new behaviour is much better than it used to be. 


One small note:

For the use case when one wants to grep something and then manually pock with results in panel works fine. 

There are use cases where I want to grep and get an editable list of results. Right now I'd just use console `rg something > results.txt` and then edit results.txt in vscode. It would be useful if GREP panel allow to copy/paste all the contents or exports to file. That would cover both use cases.

**Comment by chrisjdavies** [comment]
Nice idea. I added it as a command just now. Either right-click on the results panel or just use it from the command palette.
